
name: CI

on:
  push:
  pull_request:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }} (${{ matrix.arch }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [auto64]
        include:
          - os: ubuntu-latest
            arch: aarch64
          - os: macos-latest
            arch: arm64
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.3.1
        env:
          CIBW_BUILD: cp*
          CIBW_ARCHS: ${{ matrix.arch }}
          CIBW_BEFORE_BUILD: 'pip install -r ./requirements.txt'

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
